// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3TF5LWVLfJn30NVQWG2x3VvIkq0yHx5s',
    appId: '1:132828249791:web:b6ca9e083de2bdd316900a',
    messagingSenderId: '132828249791',
    projectId: 'notes999-4d95e',
    authDomain: 'notes999-4d95e.firebaseapp.com',
    storageBucket: 'notes999-4d95e.appspot.com',
    measurementId: 'G-TZMC9PXTSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFLpdHzmtbq0_tIJ2jL2E19LMB1r2FHMU',
    appId: '1:132828249791:android:097ec80a38c5d1bd16900a',
    messagingSenderId: '132828249791',
    projectId: 'notes999-4d95e',
    storageBucket: 'notes999-4d95e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo6YtHNmk-AQjl_HCobfnHADW32L4pkbE',
    appId: '1:132828249791:ios:9d17038eeef5633f16900a',
    messagingSenderId: '132828249791',
    projectId: 'notes999-4d95e',
    storageBucket: 'notes999-4d95e.appspot.com',
    iosClientId: '132828249791-519lsn6i0tspade9d8ugtpsmajat4bmb.apps.googleusercontent.com',
    iosBundleId: 'com.makingstuff.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo6YtHNmk-AQjl_HCobfnHADW32L4pkbE',
    appId: '1:132828249791:ios:2defb4bd5394641216900a',
    messagingSenderId: '132828249791',
    projectId: 'notes999-4d95e',
    storageBucket: 'notes999-4d95e.appspot.com',
    iosClientId: '132828249791-eji00a09h4aal2vdqu8bpq5320p4tf7e.apps.googleusercontent.com',
    iosBundleId: 'com.makingstuff.notes.RunnerTests',
  );
}
